const mongoose = require("mongoose");
const objectivesSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true },
    userId: {
      type: String,
      required: true,
      lowercase: true,
    },
    goalId: { type: String },
    goal_Id: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: "Goals",
    },
    strategic_objective: { type: String },
    functional_objective: { type: String },
    performance_indicator: { type: String },
    target: { type: Number },
    formula: { type: String },
    programs: { type: String },
    responsible_persons: { type: String, required: true },
    clients: { type: String },
    remarks: { type: String },
    // timetable: [],
    // frequency_monitoring: { type: String },

    month_0: { type: Number },
    month_0_date: { type: Date },
    month_1: { type: Number },
    month_1_date: { type: Date },
    month_2: { type: Number },
    month_2_date: { type: Date },
    month_3: { type: Number },
    month_3_date: { type: Date },
    month_4: { type: Number },
    month_4_date: { type: Date },
    month_5: { type: Number },
    month_5_date: { type: Date },
    month_6: { type: Number },
    month_6_date: { type: Date },
    month_7: { type: Number },
    month_7_date: { type: Date },
    month_8: { type: Number },
    month_8_date: { type: Date },
    month_9: { type: Number },
    month_9_date: { type: Date },
    month_10: { type: Number },
    month_10_date: { type: Date },
    month_11: { type: Number },
    month_11_date: { type: Date },

    goal_month_0: { type: Number },
    goal_month_0_date: { type: Date },
    goal_month_1: { type: Number },
    goal_month_1_date: { type: Date },
    goal_month_2: { type: Number },
    goal_month_2_date: { type: Date },
    goal_month_3: { type: Number },
    goal_month_3_date: { type: Date },
    goal_month_4: { type: Number },
    goal_month_4_date: { type: Date },
    goal_month_5: { type: Number },
    goal_month_5_date: { type: Date },
    goal_month_6: { type: Number },
    goal_month_6_date: { type: Date },
    goal_month_7: { type: Number },
    goal_month_7_date: { type: Date },
    goal_month_8: { type: Number },
    goal_month_8_date: { type: Date },
    goal_month_9: { type: Number },
    goal_month_9_date: { type: Date },
    goal_month_10: { type: Number },
    goal_month_10_date: { type: Date },
    goal_month_11: { type: Number },
    goal_month_11_date: { type: Date },

    file_month_0: { type: String },
    file_month_0_date: { type: Date },
    file_month_1: { type: String },
    file_month_1_date: { type: Date },
    file_month_2: { type: String },
    file_month_2_date: { type: Date },
    file_month_3: { type: String },
    file_month_3_date: { type: Date },
    file_month_4: { type: String },
    file_month_4_date: { type: Date },
    file_month_5: { type: String },
    file_month_5_date: { type: Date },
    file_month_6: { type: String },
    file_month_6_date: { type: Date },
    file_month_7: { type: String },
    file_month_7_date: { type: Date },
    file_month_8: { type: String },
    file_month_8_date: { type: Date },
    file_month_9: { type: String },
    file_month_9_date: { type: Date },
    file_month_10: { type: String },
    file_month_10_date: { type: Date },
    file_month_11: { type: String },
    file_month_11_date: { type: Date },

    quarter_1: { type: Number },
    quarter_1_date: { type: Date },
    quarter_2: { type: Number },
    quarter_2_date: { type: Date },
    quarter_3: { type: Number },
    quarter_3_date: { type: Date },
    quarter_0: { type: Number },
    quarter_0_date: { type: Date },

    goal_quarter_1: { type: Number },
    goal_quarter_1_date: { type: Date },
    goal_quarter_2: { type: Number },
    goal_quarter_2_date: { type: Date },
    goal_quarter_3: { type: Number },
    goal_quarter_3_date: { type: Date },
    goal_quarter_0: { type: Number },
    goal_quarter_0_date: { type: Date },

    file_quarter_1: { type: String },
    file_quarter_1_date: { type: Date },
    file_quarter_2: { type: String },
    file_quarter_2_date: { type: Date },
    file_quarter_3: { type: String },
    file_quarter_3_date: { type: Date },
    file_quarter_0: { type: String },
    file_quarter_0_date: { type: Date },

    semi_annual_0: { type: Number },
    semi_annual_0_date: { type: Date },
    semi_annual_1: { type: Number },
    semi_annual_1_date: { type: Date },

    goal_semi_annual_0: { type: Number },
    goal_semi_annual_0_date: { type: Date },
    goal_semi_annual_1: { type: Number },
    goal_semi_annual_1_date: { type: Date },

    file_semi_annual_0: { type: String },
    file_semi_annual_0_date: { type: Date },
    file_semi_annual_1: { type: String },
    file_semi_annual_1_date: { type: Date },

    yearly_0: { type: Number },
    yearly_0_date: { type: Date },
    goal_yearly_0: { type: Number },
    goal_yearly_0_date: { type: Date },
    file_yearly_0: { type: String },
    file_yearly_0_date: { type: Date },

    frequency_monitoring: {
      type: String,
      enum: ["yearly", "quarterly", "monthly", "semi_annual"], // Define allowed values
      // required: true,
    },
    // timetable: { type: String },

    complete: { type: Boolean, default: false },
    data_source: { type: String },
    budget: { type: Number, required: true },
    // campus: { type: String, required: true },
    date_added: { type: Date, required: true, default: Date.now },
    createdBy: { type: String, required: true },
    updateby: { type: String },
    updateDate: { type: Date },
    createdAt: { type: Date, default: Date.now },
    deleted: { type: Boolean, default: false },
    type_of_computation: {
      type: String,
      enum: ["cumulative", "non-cumulative"],
    },
    target_type: {
      type: String,

      enum: ["percent", "count"],
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Objective", objectivesSchema);
